name: Site Build & Publish
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: spack/setup-spack@5ab3c91bdefffffad9a7e45d1d156146afebb3a7
    - run: |
        spack mirror add develop https://binaries.spack.io/develop
        spack buildcache keys --install --trust
        spack -e . install
        echo "$(pwd)/.spack-env/view/bin" >> $GITHUB_PATH

    - run: hugo --gc --minify --baseURL "https://alecbcs.github.io"

    - uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa
      with:
        path: public/

  deploy:
    # if: github.ref == 'refs/heads/main'
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e
